### PR TITLE
Add pt_BR translation resource

### PR DESCRIPTION
**Pull request by rowanseymour**

### CODE REVIEW

**Comment by paulobernardoaf** [comment]
Hi @ericnewcomer and @rowanseymour, any news about this PR? We're very excited to see the Flow Editor in Portuguese.

**Comment by ericnewcomer** [comment]
Looking at this, for one, it modifies english to be pt, so it definitely can't be merged as is.

**Comment by rowanseymour** [comment]
Ah my bad...

**Comment by rowanseymour** [comment]
@ericnewcomer fixed now!

**Comment by rowanseymour** [comment]
@ericnewcomer I renamed the `pt` folder to `pt-br` to match the language code in Django

**Pull request merged**
