### PR TITLE
Fix gridding and parameterize it

### PR DESCRIPTION
**Pull request by ericnewcomer**
I like this better since it makes the snapping really tight in all cases, thoughts?

### CODE REVIEW

**Comment by ericnewcomer** [comment]
I like this better since it makes the snapping really tight in all cases, thoughts?

**Comment by ycleptkellan** [comment]
I could see a smaller grid being helpful for that reason and I notice it's also creating a more pronounced contrast between the canvas and the nodes (now that they aren't given a shadow while resting). That being said, this size feels a tad too small. Accentuating the snapping (perhaps by slowing the transition a little) could add character, make dragging and dropping nodes more pleasant.

**Comment by ycleptkellan** [comment]
Ah, gotcha. Not a big deal, but i'll give that a try.

**Comment by nicpottier** [comment]
I think I agree with Kellan that maybe this is a bit small, at least I don't seem to be aligning nodes very easily on the first try. (which is the whole point of snapping ya?)

**Comment by ericnewcomer** [comment]
I think I agree a bit bigger would be better. Just couldn’t easily make it work quickly without it bein divisible by 10 :)

**Comment by ericnewcomer** [comment]
Okay, sticking with grid size of 20 (_same as its always been, same as it ever was_). Would still like to merge this since I've colocated all the gridding variables and fixed some gridding math that was definitely off but only worked coincidentally.

**Comment by ericnewcomer** [comment]
Ha, me either, but really wanted it. Very well might be an anti-pattern tho.

**Pull request merged**
