### PR TITLE
Use compose component for Send Message action

### PR DESCRIPTION
**Pull request by susanm74**
fixes https://github.com/nyaruka/floweditor/issues/1182

needs to be merged AFTER https://github.com/nyaruka/floweditor/pull/1183 AND https://github.com/nyaruka/temba-components/pull/315 are merged

### CODE REVIEW

**Comment by susanm74** [comment]
BEFORE
Screen Shot 2023-04-25 at 5 14 33 PM

**Comment by susanm74** [comment]
AFTER
Screen Shot 2023-04-25 at 5 15 12 PM

**Comment by susanm74** [comment]
note - this PR is on hold for now until it's confirmed how we'll handle migration/transference of the "conditional media url" functionality inclusive of the current attachment feature in the send message action attachments tab

**Comment by ericnewcomer** [comment]
We agreed that the attachment code should work with old attachment formats as well.

**Pull request closed without merging**
