### PR TITLE
WIP: Result Count Updates

### PR DESCRIPTION
**Pull request by ycleptkellan**
- Changes `getSuggestedResultName` to only count nodes w/ msg waits.
- Changes `Response` to `Result`, as passive and hybrid splits aren't operating on a response.

### CODE REVIEW

**Comment by ycleptkellan** [comment]
Ah, dang, thanks for catching that! Riffing on this in #331, I'll let you know when it's ready for review.

**Comment by ycleptkellan** [comment]
@ericnewcomer this one's tricky in that we aren't yet maintaining a list of result names in memory (which, as you know, we'll have to do for the completion menu). Figure we should discuss expectations around that before moving forward on this. In short, no easy way to cover that edge case by my estimation.

**Comment by ericnewcomer** [comment]
Fine punting on this edge case for now

**Comment by ericnewcomer** [comment]
...so long as you file a ticket so we don't forget about it.

**Comment by ycleptkellan** [comment]
I can bite this off in a two-part PR next week if you'll be refactoring router forms. Will leave this open until we have a chance to discuss.

**Comment by ycleptkellan** [comment]
OK @ericnewcomer this one's ready for another pass. 

Once we've got this where we want it I figure one or more of the following make sense:

- Get #334 fixed so we can add logic to ensure we're removing `resultNames` from the store when the user changes a router to action.
- #104 
- #105. 

LMK what you think 👍

**Comment by ycleptkellan** [comment]
Ah, thanks. Looking into it.

**Comment by ericnewcomer** [comment]
@ycleptkellan this ready for another go?

**Comment by ycleptkellan** [comment]
No quite yet, one last thing from that merge to fix.

**Pull request merged**
