### PR TITLE
add attachments tab - upload attachment error handling

### PR DESCRIPTION
**Pull request by susanm74**
https://github.com/nyaruka/floweditor/issues/1067

### CODE REVIEW

**Comment by susanm74** [comment]
attachment uploads successful - img, audio, video
https://user-images.githubusercontent.com/854012/203505607-ddee2487-c08c-461a-b9b7-b5e26fd50f77.mov

attachment uploads failed - django errors
https://user-images.githubusercontent.com/854012/203505795-fda691ee-5e99-4303-bb6f-a0e315822248.mov

attachment uploads failed - nginx errors
https://user-images.githubusercontent.com/854012/203506104-c83c611b-85b4-48fd-996e-ec0123d705a8.mov

**Comment by susanm74** [comment]
@ericnewcomer ok this is RFR

**Comment by ericnewcomer** [comment]
It still doesn't reset the select widget in the case of upload failure, but I'm fine taking this as it is for now.

**Comment by susanm74** [comment]
@ericnewcomer ugh, yeah, i went down a smaller version of a similar rabbit hole to try and get that working, esp once we got the other scenario working (where a user uploads an attachment, and then the list re-renders with the empty option cleared out and correctly displaying "Add Attachment") but i just could not figure out why this scenario still wasn't working (where a user uploads an attachment and an error occurs... maybe is it bc there ISN'T a re-render happening?), but yeah, based on the code being so simple and just doing a check of whether it's the empty option or not, it's still bugging me!

**Comment by susanm74** [comment]
but nevertheless, thank you for merging!

**Pull request merged**
