### PR TITLE
AddURN action

### PR DESCRIPTION
**Pull request by ericnewcomer**

### CODE REVIEW

**Comment by nicpottier** [comment]
Camelcase Urn is making my eye bleed! 😭

**Comment by ericnewcomer** [comment]
So you prefer the AddURN convention I take it? That’s where I started but this is the first acronym I added and felt weird in places. I agree that probably feels overall more natural to me too though.

**Comment by nicpottier** [comment]
Ya, doesn't really matter. Probably just the bias from the Go lang where all acronyms are all caps. But I think I do prefer it.

**Comment by ericnewcomer** [comment]
Pretty sure I do too. Convinced, will change it.

**Pull request merged**
