### PR TITLE
Use engine flow type names

### PR DESCRIPTION
**Pull request by rowanseymour**
Addresses https://github.com/nyaruka/floweditor/issues/628. Might as well make these match for simplicity before we add another one.

Requires tweak on RP side but it's a nice simplification https://github.com/nyaruka/rapidpro/pull/3126

### CODE REVIEW

**Comment by rowanseymour** [comment]
I think I need to tweak https://github.com/nyaruka/floweditor/blob/7fd36e70521e9166cd0fe48ffc86c064b9c0dbb7/src/components/flow/routers/subflow/SubflowRouterForm.tsx#L109

That's currently not quite working - if you're in a Surveyor flow it seems you can enter any other kind of flow.

**Comment by ericnewcomer** [comment]
Argh, I think you've discovered another case where the big asset selector change introduced a bug. That filter should be working on native objects as they are returned from the endpoint, not the converted asset. I'll update this PR for that.

**Comment by ericnewcomer** [comment]
Oops, I take that back! This form is still using the old AssetSelection stuff, so not a bug (but would be nice to have it use temba-select based stuff like everything else (and we could likely remove react-select as a dependency in the process).

So, to answer your question, as long at the flows endpoint is returning the same things for flow_type nothing should need to change there. I pulled the corresponding rapid PR and can't reproduce the issue of surveyor flows being able to enter non-surveyor flows.

**Review by ericnewcomer — APPROVED** [review]

**Comment by rowanseymour** [comment]
I see the problem of not filtering on prod, but hadn't yet got editor working in dev mode locally to test with these changes

**Pull request merged**
