### PR TITLE
contain styles

### PR DESCRIPTION
**Pull request by ycleptkellan**
want to make sure we're scoping styles to the component so long as we can help it

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Not sure I understand here.. Isn't preview effectively a mock of an external site including / using the component?

**Comment by ycleptkellan** [comment]
sorry, perhaps i'm not clear on the intent there. are the styles under the `#flow-editor` selector simulating something a consumer would apply?

**Comment by ericnewcomer** [comment]
Yup, that is my understanding. Isn't `#flow-editor` the name of the element in the preview that's embedding our component?

**Comment by ycleptkellan** [comment]
hah wow i'm a DA, totally missed that. closing

**Pull request closed without merging**
