### PR TITLE
PUT option

### PR DESCRIPTION
**Pull request by ycleptkellan**
- refactors `WebhookRouter` to appease tslint
- adds `Methods` enum 
- adds `PUT` option

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Can't add it to the editor without also adding an issue for it on goflow

**Comment by ycleptkellan** [comment]
doh will do

**Comment by ycleptkellan** [comment]
Do you think the `Methods` enum is enough validation for now? 

https://github.com/nyaruka/goflow/issues/143

**Comment by ericnewcomer** [comment]
Ya, as long as it's restricted to the set we want, I think we are good here.

**Pull request merged**
