### PR TITLE
Add scrolling on rules localization

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
https://user-images.githubusercontent.com/1040571/116716877-8f787b80-a9d8-11eb-96ad-29c728900875.mp4

**Review by ericnewcomer — APPROVED** [review]

**Comment by ericnewcomer** [comment]
I merged this, but just noticed the following:
Screen Shot 2021-05-03 at 9 25 56 AM

**Comment by ericnewcomer** [comment]
@norkans7 if you want to fix that up, I can cut a release

**Comment by norkans7** [comment]
Have tried a hard refresh?

**Comment by norkans7** [comment]
Nyaruka Flow Editor 2021-05-03 18-37-43

@ericnewcomer

**Comment by ericnewcomer** [comment]
Yes same thing for me with a hard refresh.

**Comment by norkans7** [comment]
So far I am not able to reproduce that not even on https://floweditor.nyaruka.com/

**Comment by ericnewcomer** [comment]
I see it across Chrome, Safari, and Firefox. I can see it using long category names or just A,B,C... There must be something we are doing differently or something with your environment. Can you try emptying your browsing data? It happens for me 100% of the time with a completely clean browser.

**Comment by norkans7** [comment]
@nicpottier @rowanseymour can you help reproduce this on https://floweditor.nyaruka.com/ ?

**Comment by rowanseymour** [comment]
Captura de Pantalla 2021-05-03 a la(s) 13 54 41

**Comment by ericnewcomer** [comment]
@rowanseymour you need to make it scroll. Check now.

**Comment by rowanseymour** [comment]
Ah doh - still looks fine for me tho with scrolling

**Comment by rowanseymour** [comment]
Do you have scrollbars always visible?

**Comment by ericnewcomer** [comment]
Man, that's super weird. It looks fine on rules, but the category names are never right for me when scrolling. There must be some other difference (like auto scrollbars or who knows what).

**Comment by ericnewcomer** [comment]
Funny, we had the same thought at the same moment. Yes, if you have normal (always) scrollbars, you'll see it.

**Comment by rowanseymour** [comment]
Yeah I just noticed I can see a scrollbar in your screenshot but on my box it's impossible to screengrab them

**Comment by ericnewcomer** [comment]
The magic scrollbar thing on mac, while neat, doesn't follow the same layout as a normal scrollbar. I now remember I turned that off ages ago to avoid this exact sort of thing. In any case, @norkans7 there's your repro.

**Comment by rowanseymour** [comment]
Good call turning it off - taking one for the team!

**Pull request merged**
